### ISSUE TITLE
Generated SVGs are semitransparent

### ISSUE THREAD

**Issue by Tachi107** [xyproto/png2svg#1]
Hi, first of all thanks for this repo!
I tried to convert my profile picture to see how this tool worked, and I noticed that some SVG viewers render the image as if it were semitransparent (the input PNG is not transparent). For example, Xfce's thumbnails and [this site](https://domain-checker.valimail.com/bimi/paoloap.ml) see the transparentness, but Chromium's SVG viewer does not. 
Do you think there's a solution to this behavior?

**Comment by xyproto** [comment]
Hi! Thanks for trying out `png2svg`.

I tried converting your profile image, and (unoptimized) it resulted in a 6,2M SVG image, with no transparent rectangles. Firefox shows it correctly here. Chromium as well. (But they both take a while to draw it).

These types of large SVG images that are constructed of tons of little rectangles are quite unusual, so they are likely to uncover bugs in several different applications.

Since both Firefox and Chromium gets it right, it's tempting to say that this is a bug with the other SVG rendering engines.

Inkscape renders this image incorrectly to PNG. Perhaps it's a matter of how they interpret data that is left out of the SVG document?

I guess it boils down to the SVG standard. If the resulting SVG document is not following the standard, then there's an issue with `png2svg`, and I will try to fix it.

**Comment by Tachi107** [comment]
I think that the problem pops up especially with low resolutions.
I'm trying to set a BIMI image for my email domain. BIMI requires that the SVG follows the SVG Tiny Portable/Secure profile, that is just a subset of SVG Tiny (you can't have animations, scripts...). 
A 6 MB SVG image would be overkill, so I resized my profile picture down to 128x, and converted it with your tool. At this resolution, when scaling the image, the distance between one rectangle and another is filled with nothing, showing the colors behind the image

**Comment by xyproto** [comment]
Could you please attach the SVG?

**Comment by xyproto** [comment]
Even with `<rect stroke-width="0"` instead of just `<rect`, Inkscape renders the resulting SVG incorrectly.

Since GIMP, Firefox, Chromium and ImageMagick renders the SVG file correctly, and the SVG document itself contains no transparency, my conclusion is that this is a bug with Inkscape, Eog and the BIMI web application.

**Comment by Tachi107** [comment]
> Could you please attach the SVG?

https://mail.paoloap.ml/Tachi.svg


> Since GIMP, Firefox, Chromium and ImageMagick renders the SVG file correctly, and the SVG document itself contains no transparency, my conclusion is that this is a bug with Inkscape, Eog and the BIMI web application.

Yeah most of the time it is rendered correctly, but not when scaled, expecially when scaled up (even in Chromium)
